<?php

namespace Drupal\etree_views\Plugin\views\field;

/**
 * Handler for showing etree_item_path.
 *
 * @ingroup views_field_handlers
 *
 * @ViewsField("etree_parent_id")
 */
class ETreeParentId extends ETreeItemFieldBase {

public function query() {
  parent::query(); // TODO: Change the autogenerated stub
}
}
